# Generated by Django 5.1.7 on 2025-04-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
