# Generated by Django 5.1.7 on 2025-04-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progresses'},
        ),
    ]
